const ListadoTicketData = [
  {
    id: 1,
    titulo: 'se daño el wifi',
    prioridad: 'alta',
    estado: 'cerrado',
    categoria: 'software',
    fechadecreacion: '24-10-2022',
    horadecreacion: '8:00 am',
    fechadecierre: '24-10-2022',
    horadecierre: '10:00 am',
    
  },
  {
    id: 2,
    titulo: 'se daño el wifi',
    prioridad: 'alta',
    estado: 'abierto',
    categoria: 'software',
    fechadecreacion: '24-10-2022',
    horadecreacion: '8:00 am',
    fechadecierre: '24-10-2022',
    horadecierre: '10:00 am',
  },
  {
    id: 3,
    titulo: 'se daño el wifi',
    prioridad: 'alta',
    estado: 'cerrado',
    categoria: 'software',
    fechadecreacion: '24-10-2022',
    horadecreacion: '8:00 am',
    fechadecierre: '24-10-2022',
    horadecierre: '10:00 am',
  },
  {
    id: 4,
    titulo: 'se daño el wifi',
    prioridad: 'alta',
    estado: 'abierto',
    categoria: 'software',
    fechadecreacion: '24-10-2022',
    horadecreacion: '8:00 am',
    fechadecierre: '24-10-2022',
    horadecierre: '10:00 am',
  },
  {
    id: 5,
    titulo: 'se daño el wifi',
    prioridad: 'alta',
    estado: 'cerrado',
    categoria: 'software',
    fechadecreacion: '24-10-2022',
    horadecreacion: '8:00 am',
    fechadecierre: '24-10-2022',
    horadecierre: '10:00 am',
  },
  {
    id: 6,
    titulo: 'se daño el wifi',
    prioridad: 'alta',
    estado: 'cerrado',
    categoria: 'software',
    fechadecreacion: '24-10-2022',
    horadecreacion: '8:00 am',
    fechadecierre: '24-10-2022',
    horadecierre: '10:00 am',
  },
  {
    id: 7,
    titulo: 'se daño el wifi',
    prioridad: 'alta',
    estado: 'abierto',
    categoria: 'software',
    fechadecreacion: '24-10-2022',
    horadecreacion: '8:00 am',
    fechadecierre: '24-10-2022',
    horadecierre: '10:00 am',
  },
  {
    id: 8,
    titulo: 'se daño el wifi',
    prioridad: 'alta',
    estado: 'abierto',
    categoria: 'software',
    fechadecreacion: '24-10-2022',
    horadecreacion: '8:00 am',
    fechadecierre: '24-10-2022',
    horadecierre: '10:00 am',
  },
  {
    id: 9,
    titulo: 'se daño el wifi',
    prioridad: 'alta',
    estado: 'cerrado',
    categoria: 'software',
    fechadecreacion: '24-10-2022',
    horadecreacion: '8:00 am',
    fechadecierre: '24-10-2022',
    horadecierre: '10:00 am',
  },
  {
    id: 10,
    titulo: 'se daño el wifi',
    prioridad: 'alta',
    estado: 'abierto',
    categoria: 'software',
    fechadecreacion: '24-10-2022',
    horadecreacion: '8:00 am',
    fechadecierre: '24-10-2022',
    horadecierre: '10:00 am',
  },
]

export default ListadoTicketData
