const ListadoClientesData = [
  {
    id: 1,
    email: 'ittechnologiers@ittechnology.com',
    nombres: 'Sebastian',
    apellidos: 'Ibarra Villamil',
    telefono: '3120254521',
    compania: 'IT Technology',
    ubicacion: 'Neiva',
  },
  {
    id: 2,
    email: 'guillermo@ittechnology.com',
    nombres: 'Guillermo',
    apellidos: 'Restrepo',
    telefono: '33234532323',
    compania: 'IT Technology',
    ubicacion: 'Neiva',
  },
  {
    id: 3,
    email: 'guillermina@ittechnology.com',
    nombres: 'Guillermina',
    apellidos: 'Restrepina',
    telefono: '33234532323',
    compania: 'IT Technologina',
    ubicacion: 'Neiva',
  },
  {
    id: 4,
    email: 'guillermuno@ittechnology.com',
    nombres: 'Guillermuno',
    apellidos: 'Restrepuno',
    telefono: '33234532323',
    compania: 'IT Technologuno',
    ubicacion: 'Neiva',
  },
  {
    id: 5,
    email: 'dfsalazar@ittechology.com',
    nombres: 'Daniel Felipe',
    apellidos: 'Salazar Losada',
    telefono: '3125581958',
    compania: 'IT Technology',
    ubicacion: 'Neiva',
  },
  {
    id: 6,
    email: 'falazar@ittechology.com',
    nombres: 'Falazar',
    apellidos: 'Salazar Losada',
    telefono: '3125581958',
    compania: 'IT Technology',
    ubicacion: 'Neiva',
  },
  {
    id: 7,
    email: 'alvajpo@ittechnology.com',
    nombres: 'Alvaro',
    apellidos: 'Polania',
    telefono: '3158287458',
    compania: 'IT Technology',
    ubicacion: 'Neiva',
  },
]

export default ListadoClientesData
